version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput --username=adm --email=adm@example.com || true &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - media_data:/code/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SUPERUSER_PASSWORD=adm
      - DJANGO_SUPERUSER_USERNAME=adm
      - DJANGO_SUPERUSER_EMAIL=adm@example.com

volumes:
  media_data:
