# Generated by Django 5.1.6 on 2025-03-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_userprofile_sid"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="patronymic",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
