"""
Django settings for automaster project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

import time

print("DEBUG: DATABASE_HOST env =", os.environ.get("DATABASE_HOST"))
print("DEBUG: POSTGRES_HOST env =", os.environ.get("POSTGRES_HOST"))

print(time.time)


def getenv(name, default=None):
    return os.environ.get(name, default)


print("DEBUG: POSTGRES_HOST env =", getenv("POSTGRES_PASSWORD"))

# Security
SECRET_KEY = getenv("SECRET_KEY")
DEBUG = getenv("DEBUG", "0") == "1"
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Applications
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "service.apps.ServiceConfig",
    "django.contrib.admin",
    "crispy_forms",
    "crispy_bootstrap5",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

# Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "automaster",
        "USER": "automasteruser",
        "PASSWORD": getenv("POSTGRES_PASSWORD"),
        "HOST": getenv("DATABASE_HOST", "postgres"),
        "PORT": "5432",
    }
}

# Keycloak
KEYCLOAK_SERVER_URL = "http://keycloak:8080/"
KEYCLOAK_REALM = "automaster"
KEYCLOAK_CLIENT_ID = "automaster-client"
KEYCLOAK_CLIENT_SECRET = getenv("KEYCLOAK_CLIENT_SECRET")
# KEYCLOAK_SERVER_URL = "http://localhost:8080/"
# KEYCLOAK_REALM = "automaster"
# KEYCLOAK_CLIENT_ID = "automaster-client"
# KEYCLOAK_CLIENT_SECRET = "5zVRqmOzdbdaBPPJLK4CcD0Qx94V31zB"
CORS_ALLOWED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

SOCIAL_AUTH_PKCE_CODE_VERIFIER = True
SESSION_COOKIE_SECURE = False  # Для разработки

SOCIAL_AUTH_KEYCLOAK_KEY = KEYCLOAK_CLIENT_ID
SOCIAL_AUTH_KEYCLOAK_SECRET = KEYCLOAK_CLIENT_SECRET
SOCIAL_AUTH_KEYCLOAK_SCOPE = ["openid", "profile", "email", "roles", "phone"]
SOCIAL_AUTH_KEYCLOAK_AUTH_EXTRA_ARGUMENTS = {
    "code_challenge_method": "S256",
    "scope": "openid profile email",
}

# PKCE Settings
SOCIAL_AUTH_PKCE_CODE_VERIFIER = True
SOCIAL_AUTH_KEYCLOAK_USE_PKCE = True
SOCIAL_AUTH_KEYCLOAK_CODE_CHALLENGE_METHOD = "S256"

# OIDC Endpoints
SOCIAL_AUTH_KEYCLOAK_OIDC_ENDPOINT = f"{KEYCLOAK_SERVER_URL}realms/{KEYCLOAK_REALM}"
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = (
    f"{SOCIAL_AUTH_KEYCLOAK_OIDC_ENDPOINT}/protocol/openid-connect/auth"
)
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL = (
    f"{SOCIAL_AUTH_KEYCLOAK_OIDC_ENDPOINT}/protocol/openid-connect/token"
)
SOCIAL_AUTH_KEYCLOAK_USERINFO_URL = (
    f"{SOCIAL_AUTH_KEYCLOAK_OIDC_ENDPOINT}/protocol/openid-connect/userinfo"
)
SOCIAL_AUTH_KEYCLOAK_LOGOUT_URL = (
    f"{SOCIAL_AUTH_KEYCLOAK_OIDC_ENDPOINT}/protocol/openid-connect/logout"
)
SOCIAL_AUTH_KEYCLOAK_JWKS_URI = (
    f"{SOCIAL_AUTH_KEYCLOAK_OIDC_ENDPOINT}/protocol/openid-connect/certs"
)

# JWT Configuration
SOCIAL_AUTH_OIDC_ENABLED = True
SOCIAL_AUTH_OIDC_VERIFY_JWT = True
SOCIAL_AUTH_OIDC_VERIFY_ISS = True
SOCIAL_AUTH_OIDC_VERIFY_AUD = True
JWT_ALGORITHM = "RS256"

# Session Configuration
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False  # True for production
CSRF_COOKIE_SECURE = False  # True for production
CSRF_TRUSTED_ORIGINS = ["http://localhost:8000"]

# URLs
LOGIN_URL = "login"
LOGOUT_URL = "logout"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/"
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = "/"
SOCIAL_AUTH_LOGIN_ERROR_URL = "/login-error/"
SOCIAL_AUTH_INACTIVE_USER_URL = "/inactive/"

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "service.pipeline.get_keycloak_sub",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "service.pipeline.save_keycloak_data",
)
SOCIAL_AUTH_KEYCLOAK_ID_KEY = "sub"


# Отключаем генерацию username
SOCIAL_AUTH_NO_DEFAULT_PROTECTED_USER_FIELDS = True
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = False
# Other settings
ROOT_URLCONF = "automaster.urls"
WSGI_APPLICATION = "automaster.wsgi.application"
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "social": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}


SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = False  # Отключаем ассоциацию по email
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = False


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
